name: Sahar

on:
 push:
    branches:
      - main

jobs:
 Test1:
   runs-on: ubuntu-latest
   steps:
    - name: Echo1
      run: echo devops1
 
 Test2:
   runs-on: ubuntu-latest
   needs: Test
   steps:
    - name: Echo2
      run: echo devops2